export const primeConfig = {
  ripple: true,
  translation: {
    startsWith: 'Começar por',
    contains: 'Contém',
    notContains: 'Não contém',
    endsWith: 'Termina com',
    equals: 'Igual',
    notEquals: 'Diferente',
    noFilter: 'Sem filtro',
    lt: 'Menor que',
    lte: 'Menor ou igual a',
    gt: 'Maior que',
    gte: 'Maior ou igual a',
    dateIs: 'Data é',
    dateIsNot: 'Data não é',
    dateBefore: 'Data antes',
    dateAfter: 'Data depois',
    clear: 'Limpar',
    apply: 'Aplicar',
    matchAll: 'Corresponder a todos',
    matchAny: 'Corresponder a qualquer',
    addRule: 'Adicionar regra',
    removeRule: 'Remover regra',
    accept: 'Sim',
    reject: 'Não',
    choose: 'Escolher',
    upload: 'Enviar',
    cancel: 'Cancelar',
    pending: 'Pendente',
    dayNames: [
      'Domingo',
      'Segunda',
      'Terça',
      'Quarta',
      'Quinta',
      'Sexta',
      'Sábado',
    ],
    dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    monthNames: [
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro',
    ],
    monthNamesShort: [
      'Jan',
      'Fev',
      'Mar',
      'Abr',
      'Mai',
      'Jun',
      'Jul',
      'Ago',
      'Set',
      'Out',
      'Nov',
      'Dez',
    ],
    chooseYear: 'Escolher ano',
    chooseMonth: 'Escolher mês',
    chooseDate: 'Escolher data',
    prevDecade: 'Década anterior',
    nextDecade: 'Próxima década',
    prevYear: 'Ano anterior',
    nextYear: 'Próximo ano',
    prevMonth: 'Mês anterior',
    nextMonth: 'Próximo mês',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Próximo minuto',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Próximo segundo',
    am: 'AM',
    pm: 'PM',
    today: 'Hoje',
    weekHeader: 'Sem',
    firstDayOfWeek: 0,
    dateFormat: 'dd/mm/yyyy',
    weak: 'Fraco',
    medium: 'Médio',
    strong: 'Forte',
    passwordPrompt: 'Digite uma senha',
    emptyFilterMessage: 'Nenhum resultado encontrado',
    searchMessage: 'Procurar',
    selectionMessage: 'Selecione',
    emptySelectionMessage: 'Nenhum registro selecionado',
    emptySearchMessage: 'Nenhum resultado encontrado',
    emptyMessage: 'Nenhum registro encontrado',
    aria: {
      trueLabel: 'Sim',
      falseLabel: 'Não',
      stars: '{star} estrelas',
      selectAll: 'Selecionar todos',
      unselectAll: 'Desmarcar todos',
      close: 'Fechar',
      previous: 'Anterior',
      next: 'Próximo',
      navigation: 'Navegação',
      scrollTop: 'Rolar para o topo',
      moveTop: 'Mover para o topo',
      moveUp: 'Mover para cima',
      moveDown: 'Mover para baixo',
      moveBottom: 'Mover para o final',
      moveToTarget: 'Mover para o alvo',
      moveToSource: 'Mover para a fonte',
      moveAllToTarget: 'Mover todos para o alvo',
      moveAllToSource: 'Mover todos para a fonte',
      pageLabel: '{page}',
      firstPageLabel: 'Primeira página',
      lastPageLabel: 'Última página',
      nextPageLabel: 'Próxima página',
      prevPageLabel: 'Página anterior',
      rowsPerPageLabel: 'Linhas por página',
      jumpToPageDropdownLabel: 'Pular para a página',
      jumpToPageInputLabel: 'Digite um número de página',
      selectRow: 'Selecionar linha',
      unselectRow: 'Desmarcar linha',
      expandRow: 'Expandir linha',
      collapseRow: 'Recolher linha',
      showFilterMenu: 'Mostrar menu de filtro',
      hideFilterMenu: 'Ocultar menu de filtro',
      filterOperator: 'Operador de filtro',
      filterConstraint: 'Restrição de filtro',
      editRow: 'Editar linha',
      saveEdit: 'Salvar edição',
      cancelEdit: 'Cancelar edição',
      listView: 'Visualização de lista',
      gridView: 'Visualização de grade',
      slide: 'Deslizar',
      slideNumber: '{slideNumber}',
      zoomImage: 'Ampliar imagem',
      zoomIn: 'Ampliar',
      zoomOut: 'Reduzir',
      rotateRight: 'Girar para a direita',
      rotateLeft: 'Girar para a esquerda',
    },
  },
};
